### ISSUE TITLE
django.contrib.gis.geos.error.GEOSException: Could not parse version info string "3.6.2-CAPI-1.10.2 4d2925d6"

### ISSUE THREAD

**Issue by WinnyTroy** [onaio/kpi#14]
```python
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/winny/.pyenv/versions/2.7.16/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 41, in <module>
    class Permission(models.Model):
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/db/models/base.py", line 139, in __new__
    new_class.add_to_class('_meta', Options(meta, **kwargs))
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/db/models/base.py", line 324, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/db/models/options.py", line 250, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/db/__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/db/utils.py", line 241, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/db/utils.py", line 112, in load_backend
    return import_module('%s.base' % backend_name)
  File "/home/winny/.pyenv/versions/2.7.16/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/base.py", line 8, in <module>
    from .features import DatabaseFeatures
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/contrib/gis/db/backends/postgis/features.py", line 1, in <module>
    from django.contrib.gis.db.backends.base.features import BaseSpatialFeatures
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/contrib/gis/db/backends/base/features.py", line 3, in <module>
    from django.contrib.gis.db.models import aggregates
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/contrib/gis/db/models/__init__.py", line 7, in <module>
    from django.contrib.gis.geos import HAS_GEOS
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/contrib/gis/geos/__init__.py", line 8, in <module>
    from .libgeos import geos_version, geos_version_info  # NOQA: flake8 detects only the last __all__
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/contrib/gis/geos/libgeos.py", line 152, in <module>
    _verinfo = geos_version_info()
  File "/home/winny/.pyenv/versions/kpi_local/lib/python2.7/site-packages/django/contrib/gis/geos/libgeos.py", line 147, in geos_version_info
    raise GEOSException('Could not parse version info string "%s"' % ver)
django.contrib.gis.geos.error.GEOSException: Could not parse version info string "3.6.2-CAPI-1.10.2 4d2925d6"
```

**Comment by WinnyTroy** [comment]
The dirty fix currently being used is by following [this solution](https://stackoverflow.com/questions/18643998/geodjango-geosexception-error?answertab=votes#tab-top)


Would be cool if we could get a better way to work around this than editing django files?

**Comment by WinnyTroy** [comment]
This is no longer an issue as we are now using Django 2.2 and do not need to specify this path separately.
